### ISSUE TITLE
DataServiceVersion Response Header Missing After Compression

### ISSUE THREAD

**Issue by MartynJones87** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#12]
Hello,

I've tried using the library to compress the responses coming from a Web API OData controller and the compression works great, except for that the response does not contain a header for DataServiceVersion which it did before using the compression. 

This header being missing causes Breeze to fail parsing the response on the client side with a vague error message of "; ", which I've traced to a "no handler for data" error in datajs caused by the missing header.

Thanks very much,

Martyn.

**Comment by azzlack** [comment]
Fixed in e17c064d87ab09a8d0927cbcb333936ed2da6e10
