### ISSUE TITLE
Error: Server cannot append header after HTTP headers have been sent

### ISSUE THREAD

**Issue by VanHelSeenG** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#13]
After some tests with turned on GZip compression I found what CompressionHandler generate this exception. An exception occurs most often during server get unauthorized requests and sometimes during authorized.I use ordinary OWIN OAuth. Exception also occurs when I send request to auth /token endpoint. I attached screenshot of stack trace(begin of it). Please, help with problem
![image](https://cloud.githubusercontent.com/assets/4726930/7788642/fe38ee64-024b-11e5-8def-62777c67bc26.png)

**Comment by azzlack** [comment]
This is related to OWIN: http://katanaproject.codeplex.com/discussions/540202  

According to them, it is fixed in .NET 4.6, but I will see if I can find a workaround for this version.

**Comment by fr4nky80** [comment]
solution for this?

**Comment by pranaydutta89** [comment]
:+1:

**Comment by pcoulter** [comment]
(bump)

**Comment by azzlack** [comment]
This is fixed in `.NET 4.6`, you need to recompile your project to use that and set the following options in your web.config

```xml
<system.web> 
    <compilation targetFramework="4.6"/> 
    <httpRuntime targetFramework="4.6" /> 
</system.web> 
```

**Comment by azzlack** [comment]
So. This will be solved by downloading an extra package that contains a special `OwinServerCompressionHandler`. This is a separate package because the base package does not require Owin.

**Comment by HughJeffner** [comment]
I have a somewhat strange setup using Owin + Identity + `CookieAuthenticationMiddleware` and the `OwinServerCompressionHandler` fails to detect the headers have already been sent.  I use `AuthenticationManager.SignIn` and `AuthenticationManager.SignOut` methods in my controller and this is what ultimately modifies the headers by inserting some cookies into the response.  The exception is thrown on a background thread and the set-cookie headers never make it into the response.

The current workaround is to disable compression for these methods which isn't a big deal.  It just took many hours of detective work to figure out this module was the cause :mag: :frowning:
