### ISSUE TITLE
Remove Microsoft.Bcl dependency in .net4.5

### ISSUE THREAD

**Issue by brenovieira** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#17]
It would be nice if there weren't these dependencies when targeting .net 4.5 (or 4.5.2 in my use case):
```Microsoft.Bcl```, ```Microsoft.Bcl.Build```, ```Microsoft.Bcl.Compression```.

AFAIK, these packages are used only for backward compatibility with .net 4, for example, to use ```async await```. But in .net 4.5, I don't need them.

In my project these 3 packages were added just to use ```Microsoft.AspNet.WebApi.MessageHandlers.Compression```.

What do you think ?

**Comment by mihasic** [comment]
Microsoft.Bcl.Compression is not for .net 4 (it doesn't even support it).
It was renamed to System.IO.Compression, but the later is still a [pre-release](https://github.com/dotnet/core/blob/master/release-notes/System.IO.Compression.md).

**Comment by gdoron** [comment]
+1

**Comment by azzlack** [comment]
Fixed in cf3ccea2c54fe62aeae4aa783ba5fc7e352ee70b
