### ISSUE TITLE
compressing even when accept encoding is null

### ISSUE THREAD

**Issue by pranaydutta89** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#21]
i am making a console app and with help of easyhttp i am making  a call to server,the problem is ,that server is is still compressing the data even when accept-encoding is null,  please help me to pin down the issue ??

**Comment by azzlack** [comment]
Fixed in commit 867ff8cdc7314d363d02ab431b2161195d354bf3

**Comment by pranaydutta89** [comment]
Hi @azzlack 
  is the above issue fixed ,because i am using postman and there i am not passing accept encoding still its compressing in gzip
