### ISSUE TITLE
UWP projects referencing Microsoft.AspNet.WebApi.MessageHandlers.Compression does not compile.

### ISSUE THREAD

**Issue by kiewic** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#23]
When creating a Universal Windows Platform app and installing the **Microsoft.AspNet.WebApi.MessageHandlers.Compression** package, building the project fails with:

> Type universe cannot resolve assembly: System.Web.Http, Version=5.2.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.

Installing one version earlier works fine.

More info here: http://stackoverflow.com/questions/34187169/odata-v-4-compression-support-in-uwp-windows-10-mobile?noredirect=1#comment56192795_34187169

**Comment by azzlack** [comment]
Fixed in commit cf3ccea2c54fe62aeae4aa783ba5fc7e352ee70b
