### ISSUE TITLE
Why the dependency on Microsoft.Bcl.Compression in a .NET 4.5.1 targeted project?

### ISSUE THREAD

**Issue by martyt** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#32]
My project currently targets .NET 4.5.1, which as I understand it, already includes the GZipStream / DeflateStream classes that are brought in by the Microsoft.Bcl.Compression package. 

Adding any of the ".Bcl.*" packages causes no end of grief, as I then get a warning in every assembly that reference my project complaining that it, too, must install Microsoft.Bcl.Build

Am I missing something or should your package not require Microsoft.Bcl.Compression if the project it's being installed to already targets .Net 4.5 or later?

**Comment by azzlack** [comment]
The latest version (2.0.0 and upwards) should not require the BCL libs at all, which version do you have installed?

**Comment by martyt** [comment]
I installed v2.0.3 into a project targeting .NET 4.5.1
