### ISSUE TITLE
ObjectDisposedException - BaseServerCompressionHandler throws stream of response.Content has already been disposed.

### ISSUE THREAD

**Issue by gentledepp** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#34]
I am using this library in conjunction with AspNET Boilerplate.
This is a very good framework for building websites based on .NET.
One thing it does is to create the JQuery rest service proxies for Web API services.
The problem with this feature is, that the response.Contents underlying stream has already been disposed, when BaseSErverCompressionHandler tries to compress it.

Simplest solution would be to catch the ObjectDisposedException and return the uncompressed response. That way the site remains functional at least.

**Comment by azzlack** [comment]
Thanks for the PR, will have a new version out soon
