### ISSUE TITLE
Should be using RecyclableMemoryStream

### ISSUE THREAD

**Issue by damianh** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#36]
This code [here](https://github.com/azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression/blob/develop/src/Core/Compressors/BaseCompressor.cs#L45) should be using [RecycleableMemoryStream](https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream)

http://www.philosophicalgeek.com/2015/02/06/announcing-microsoft-io-recycablememorystream/

**Comment by damianh** [comment]
I'd be happy to send PR if you agree :)

**Comment by azzlack** [comment]
That looks extremely interesting. If you make a PR, I'll integrate it :-)
