### ISSUE TITLE
Usage of this library in an API Proxy environment - autodetection of already compressed response bodies

### ISSUE THREAD

**Issue by meinbrodt** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#37]
Hi, 

I'm using an API Proxy to route API requests coming from a Javascript client to it's final API endpoint.Once the response gets in from the API endpoint I send it back to the client that initiated the request.

The API endpoint mostly sends back uncompressed JSON and XML responses to the API Proxy. My idea is now that I want to use your library in order to at least compress the response from the API Proxy to the final client.

However, I can't be sure that the developers who manage the API endpoint will eventually implement compressed responses in the future. Therefore I wanted to know if your library detects already compressed response bodies and doesn't perform a new compression in those cases.

Best regards and thanks, Matthias

**Comment by azzlack** [comment]
There

**Comment by ghost** [comment]
I'm a little late, but thanks for the fix.
