### ISSUE TITLE
Content headers missing from the request during compression

### ISSUE THREAD

**Issue by nikhilshilimkar** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#38]
Hi,

I see that the content headers are missing from the request during compression while the request size is more than 860 bytes. After debugging I came to know that the headers are ignored in the CopyTo() extension method([here](https://github.com/azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression/blob/develop/src/Core/Extensions/HttpContentHeaderExtensions.cs#L29) and [here](https://github.com/azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression/blob/develop/src/Core/Extensions/HttpContentHeaderExtensions.cs#L34)). I had a Content-Length header in the request which lead the CopyTo() to return without copying the headers from the request to the target headers. Hence lead to missing of the headers from the request. I feel that instead of return statement it should have been continue so that the other headers can be copied to the target. 

Please let me know if I am doing something wrong.

Thanks in advance.

**Comment by nikhilshilimkar** [comment]
Hi,

Did you got time to have a look at this issue

**Comment by azzlack** [comment]
Hi and sorry for the late response. Overwriting Content-Encoding and Content-Length is intentional. Since we are compressing the content the length should be changed, as for the Content-Encoding, i guess that it is not necessary to clear it, just append to it.

Will make a change later today and push it out
