### ISSUE TITLE
Compression not working in a published webapi

### ISSUE THREAD

**Issue by TheNightFall** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#40]
During Tests, the compression works as expected, either in Debug or Release (using IISExpresss).

In production (IIS version 7.5.7600.16385) there is no compression to any requests.
Even if I enable dynamic content compression by the Compression setting on IIS, the server doesn't compress the data.

I detect the compressed response by checking the Response Header property named "Content-Encoding" which is always "gzip" in my case if succeeded.

Am I missing something? Can you help me?

**Comment by azzlack** [comment]
Hi, you shouldnt have to enable IIS compression for this to work.
That said, are there any errors in production?

**Comment by MatheusLFreitas** [comment]
It turned out that was the antivirus the was uncompressing the packages for inspection. 
I disabled it and the reponse arrived correctly. It took me a week to figure out :angry: 

Thanks
