### ISSUE TITLE
Correct config line for OWIN Webapi?

### ISSUE THREAD

**Issue by ChristineBoersen** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#43]
Minor issue, when sending identical 5.2KB packets, I tried inserting the following code into my startup.cs, I was not getting compression.

GlobalConfiguration.Configuration.MessageHandlers.Insert(0, new OwinServerCompressionHandler(new GZipCompressor(), new DeflateCompressor()));

Once I switched to using the alternate initialization code things worked as expected.
config.MessageHandlers.Insert(0, new OwinServerCompressionHandler(new GZipCompressor(), new DeflateCompressor()));

**Comment by azzlack** [comment]
That is probable because `GlobalConfiguration.Configuration` is not the same as your `config` instance. This is especially true for OWIN based setups.

Anyways, glad you got it working :-)

**Comment by ChristineBoersen** [comment]
I suspected as much myself, you might want to list both config options on the docs again for OWIN setups :)

Thanks again, and nice integration work!

**Comment by iainprior-diligent** [comment]
This just happened to me too, please can you update the doc on the main page?
