### ISSUE TITLE
The link to the license on the nuget.org page is broken

### ISSUE THREAD

**Issue by smarts** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#47]
1. go [here](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Extensions.Compression.Server/2.0.3)
1. try to click the *License* link on the left
1. see that there is no license

**Comment by azzlack** [comment]
Sorry about that. You can find the license here http://www.eyecatch.no/license/
Will fix later today

**Comment by smarts** [comment]
That link in your reply is broken, but it looks like you fixed the link on the nuget.org page. Thanks!

**Comment by smarts** [comment]
Broken again.

**Comment by Julie-House** [comment]
Could really do with this being fixed please. We are now using a tool to scan for licences and it flags this as not having a valid licence because the link is broken :(
