### ISSUE TITLE
Does not compress in PostAsJsonAsync with threshold

### ISSUE THREAD

**Issue by hansmaad** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#5]
I am using following test code

    var client = new HttpClient(new ClientCompressionHandler(
      this.server, 20, new GZipCompressor(), new DeflateCompressor()));

    client.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));
    client.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("deflate"));

    var response = await client.PostAsJsonAsync("http://localhost:55399/api/test", 
      new { text = "lalelu die katze fliegt in schuh"});

In `ClientCompressionHandler.CompressRequest(HttpRequestMessage request)` no compression is done since `request.Content.Headers.ContentLength` is `null`.

Not sure if this makes sense, but the following changes help in case of ObjectContent where `ContentLength == null`.

        private async Task CompressRequest(HttpRequestMessage request)
        {
            // As per RFC2616.14.3:
            // Ignores encodings with quality == 0
            // If multiple content-codings are acceptable, then the acceptable content-coding with the highest non-zero qvalue is preferred.
            var compressor = (from encoding in request.Headers.AcceptEncoding
                              let quality = encoding.Quality ?? 1.0
                              where quality > 0
                              join c in this.Compressors on encoding.Value.ToLowerInvariant() equals
                                  c.EncodingType.ToLowerInvariant()
                              orderby quality descending
                              select c).FirstOrDefault();

            if (compressor != null)
            {
                try
                {
                    // BEGIN
                    if (request.Content.Headers.ContentLength == null)
                        await request.Content.LoadIntoBufferAsync();
                    // END
 
                    // Only compress request if size is larger than threshold (if set)
                    if (this.contentSizeThreshold == 0)
                    {
                        request.Content = new CompressedContent(request.Content, compressor);
                    }
                    else if (this.contentSizeThreshold > 0 && request.Content.Headers.ContentLength >= this.contentSizeThreshold)
                    {
                        request.Content = new CompressedContent(request.Content, compressor);
                    }
                }
                catch (Exception ex)
                {
                    throw new Exception(string.Format("Unable to compress request using compressor '{0}'", compressor.GetType()), ex);
                }
            }
        }

**Comment by azzlack** [comment]
Possibly related to issue #14
