### ISSUE TITLE
package path is too long for Jenkins

### ISSUE THREAD

**Issue by vadzvnik** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#50]
Hello,

package path is too long.

Jenkins can't build the project with this nuget package ::
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

packages\System.Net.Http.Extensions.Compression.Client.2.0.5\lib\portable-net45+wp8+wpa81+win8+monoandroid+monotouch+Xamarin.iOS+Xamarin.Mac\System.Net.Http.Extensions.Compression.Client.dll

Thank you for the handler anyway

**Comment by whench18** [comment]
hi, for any path too long issues you can try the long path tool. this will help you solve all path too long issues. this tool is proven by many users and it is said to be really good.
