### ISSUE TITLE
can i use this in .net core 2.1

### ISSUE THREAD

**Issue by vikasNew** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#59]
i have my web API written in .net core 2.1 & andriod, ios clients are using these Web Api's.

so can i use this in my scenario?

Thanks in anticipation.

**Comment by maxdeviant** [comment]
@vikasNew ASP.NET Core has response compression built-in, so I don't think you would need this library. See [here](https://docs.microsoft.com/en-us/aspnet/core/performance/response-compression?view=aspnetcore-3.0).
