### ISSUE TITLE
This package is obsolete, so what should we be using instead?

### ISSUE THREAD

**Issue by justintoth** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#60]
"NOTE!!!

This is an obsolete package, it only installs the Microsoft.AspNet.WebApi.Extensions.Compression.Server and System.Net.Http.Extensions.Compression.Client packages."

...So what should we be using instead?

**Comment by jack128** [comment]
Microsoft.AspNet.WebApi.Extensions.Compression.Server or/and System.Net.Http.Extensions.Compression.Client
