### ISSUE TITLE
Assembly does not have a strong name

### ISSUE THREAD

**Issue by MikeChristensen** [azzlack/Microsoft.AspNet.WebApi.MessageHandlers.Compression#9]
This assembly is not signed with a key, which makes it impossible to use with assemblies that must be GAC'ed.

**Comment by damianh** [comment]
:-1:

**Comment by azzlack** [comment]
I'll make a separate nuget package for with strong naming, as this will have major implications for most devs

**Comment by marek-benes** [comment]
Is nuget packege with signed version available now?

**Comment by eaidland** [comment]
Also waiting for signed version. Any news?

**Comment by prettycode** [comment]
+1 Can't include this much-needed nuget package with our solution because of strong naming issue.

**Comment by deenairn** [comment]
+1 - would make this package extremely useful for us. Really love it's simplicity to use.

**Comment by damianh** [comment]
-1 because nobody loves binding redirects crapping all over their
app.configs
